### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by GonxoMR** [patheard/aws-fastapi-lambda#9]
Hello Patheard,

Thank you very much for this work, it brings `mangum` to an actionable level. I just wonder why there is a `sqs` module as it is not mentioned in the walkthrough nor in the `README`. I think the answer is no, but is the `sqs` necessary to deploy the infra in aws? 

Thank you in advance.

**Comment by patheard** [comment]
Glad it's useful for you.  To answer your question, no, `sqs` isn't necessary to deploy the infra.  It was something I had been playing around with, but never got finished 😅 

You can safely remove it from the Terraform.
